# Generated by Django 5.2.4 on 2025-08-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=40)),
                ('cf', models.CharField(max_length=16)),
                ('indirizzo', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dataNas', models.DateField()),
            ],
        ),
    ]
