# Generated by Django 5.2.4 on 2025-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nAbb', models.IntegerField()),
                ('cliente', models.IntegerField()),
                ('inizio', models.DateField()),
                ('fine', models.DateField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=40)),
                ('cf', models.CharField(max_length=16)),
                ('indirizzo', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dataNas', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FasciaOraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.IntegerField()),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('durata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.IntegerField()),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('nProg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nProg', models.IntegerField()),
                ('cliente', models.IntegerField()),
                ('sala', models.IntegerField()),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('posto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('tema', models.TextField()),
                ('mq', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubAbbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenotazione', models.IntegerField()),
                ('abbonamento', models.IntegerField()),
            ],
        ),
    ]
